{'properties': {'autoRecalc': 'ON_CHANGE',
                'defaultFormat': {'backgroundColor': {'blue': 1,
                                                      'green': 1,
                                                      'red': 1},
                                  'padding': {'bottom': 2,
                                              'left': 3,
                                              'right': 3,
                                              'top': 2},
                                  'textFormat': {'bold': False,
                                                 'fontFamily': 'arial,sans,sans-serif',
                                                 'fontSize': 10,
                                                 'foregroundColor': {},
                                                 'italic': False,
                                                 'strikethrough': False,
                                                 'underline': False},
                                  'verticalAlignment': 'BOTTOM',
                                  'wrapStrategy': 'OVERFLOW_CELL'},
                'locale': 'en_US',
                'timeZone': 'America/Denver',
                'title': 'Stock Results - Robinhood'},
 'sheets': [{'data': [{'columnMetadata': [{'pixelSize': 43},
                                          {'pixelSize': 107},
                                          {'pixelSize': 32},
                                          {'pixelSize': 108},
                                          {'pixelSize': 33},
                                          {'pixelSize': 70},
                                          {'pixelSize': 65},
                                          {'pixelSize': 14}],
                       'rowData': [{'values': [{'effectiveFormat': {'backgroundColor': {'blue': 1,
                                                                                        'green': 1,
                                                                                        'red': 1},
                                                                    'horizontalAlignment': 'RIGHT',
                                                                    'hyperlinkDisplayType': 'PLAIN_TEXT',
                                                                    'padding': {'bottom': 2,
                                                                                'left': 3,
                                                                                'right': 3,
                                                                                'top': 2},
                                                                    'textFormat': {'bold': False,
                                                                                   'fontFamily': 'Arial',
                                                                                   'fontSize': 10,
                                                                                   'foregroundColor': {},
                                                                                   'italic': False,
                                                                                   'strikethrough': False,
                                                                                   'underline': False},
                                                                    'verticalAlignment': 'BOTTOM',
                                                                    'wrapStrategy': 'OVERFLOW_CELL'},
                                                'effectiveValue': {'numberValue': 43784},
                                                'formattedValue': '43784',
                                                'userEnteredValue': {'numberValue': 43784}},
                                               {'effectiveFormat': {'backgroundColor': {'blue': 1,
                                                                                        'green': 1,
                                                                                        'red': 1},
                                                                    'horizontalAlignment': 'LEFT',
                                                                    'hyperlinkDisplayType': 'PLAIN_TEXT',
                                                                    'padding': {'bottom': 2,
                                                                                'left': 3,
                                                                                'right': 3,
                                                                                'top': 2},
                                                                    'textFormat': {'bold': False,
                                                                                   'fontFamily': 'Arial',
                                                                                   'fontSize': 10,
                                                                                   'foregroundColor': {},
                                                                                   'italic': False,
                                                                                   'strikethrough': False,
                                                                                   'underline': False},
                                                                    'verticalAlignment': 'BOTTOM',
                                                                    'wrapStrategy': 'OVERFLOW_CELL'},
                                                'effectiveValue': {'stringValue': 'Cash'},
                                                'formattedValue': 'Cash',
                                                'userEnteredValue': {'stringValue': 'Cash'}},
                                               {'effectiveFormat': {'backgroundColor': {'blue': 1,
                                                                                        'green': 1,
                                                                                        'red': 1},
                                                                    'horizontalAlignment': 'RIGHT',
                                                                    'hyperlinkDisplayType': 'PLAIN_TEXT',
                                                                    'padding': {'bottom': 2,
                                                                                'left': 3,
                                                                                'right': 3,
                                                                                'top': 2},
                                                                    'textFormat': {'bold': False,
                                                                                   'fontFamily': 'Arial',
                                                                                   'fontSize': 10,
                                                                                   'foregroundColor': {},
                                                                                   'italic': False,
                                                                                   'strikethrough': False,
                                                                                   'underline': False},
                                                                    'verticalAlignment': 'BOTTOM',
                                                                    'wrapStrategy': 'OVERFLOW_CELL'},
                                                'effectiveValue': {'numberValue': 0},
                                                'formattedValue': '0',
                                                'userEnteredValue': {'formulaValue': '=GOOGLEFINANCE("AKS")*INDIRECT("H"&ROW())'}},
                                               {'effectiveFormat': {'backgroundColor': {'blue': 1,
                                                                                        'green': 1,
                                                                                        'red': 1},
                                                                    'horizontalAlignment': 'LEFT',
                                                                    'hyperlinkDisplayType': 'PLAIN_TEXT',
                                                                    'padding': {'bottom': 2,
                                                                                'left': 3,
                                                                                'right': 3,
                                                                                'top': 2},
                                                                    'textFormat': {'bold': False,
                                                                                   'fontFamily': 'Arial',
                                                                                   'fontSize': 10,
                                                                                   'foregroundColor': {},
                                                                                   'italic': False,
                                                                                   'strikethrough': False,
                                                                                   'underline': False},
                                                                    'verticalAlignment': 'BOTTOM',
                                                                    'wrapStrategy': 'OVERFLOW_CELL'},
                                                'effectiveValue': {'stringValue': 'Hypothetical '
                                                                                  'Sale'},
                                                'formattedValue': 'Hypothetical '
                                                                  'Sale',
                                                'userEnteredValue': {'stringValue': 'Hypothetical '
                                                                                    'Sale'}},
                                               {'effectiveFormat': {'backgroundColor': {'blue': 1,
                                                                                        'green': 1,
                                                                                        'red': 1},
                                                                    'horizontalAlignment': 'LEFT',
                                                                    'hyperlinkDisplayType': 'PLAIN_TEXT',
                                                                    'padding': {'bottom': 2,
                                                                                'left': 3,
                                                                                'right': 3,
                                                                                'top': 2},
                                                                    'textFormat': {'bold': False,
                                                                                   'fontFamily': 'Arial',
                                                                                   'fontSize': 10,
                                                                                   'foregroundColor': {},
                                                                                   'italic': False,
                                                                                   'strikethrough': False,
                                                                                   'underline': False},
                                                                    'verticalAlignment': 'BOTTOM',
                                                                    'wrapStrategy': 'OVERFLOW_CELL'},
                                                'effectiveValue': {'stringValue': 'AKS'},
                                                'formattedValue': 'AKS',
                                                'userEnteredValue': {'stringValue': 'AKS'}},
                                               {'effectiveFormat': {'backgroundColor': {'blue': 1,
                                                                                        'green': 1,
                                                                                        'red': 1},
                                                                    'horizontalAlignment': 'LEFT',
                                                                    'hyperlinkDisplayType': 'PLAIN_TEXT',
                                                                    'padding': {'bottom': 2,
                                                                                'left': 3,
                                                                                'right': 3,
                                                                                'top': 2},
                                                                    'textFormat': {'bold': False,
                                                                                   'fontFamily': 'Arial',
                                                                                   'fontSize': 10,
                                                                                   'foregroundColor': {},
                                                                                   'italic': False,
                                                                                   'strikethrough': False,
                                                                                   'underline': False},
                                                                    'verticalAlignment': 'BOTTOM',
                                                                    'wrapStrategy': 'OVERFLOW_CELL'},
                                                'effectiveValue': {'stringValue': 'Robinhood'},
                                                'formattedValue': 'Robinhood',
                                                'userEnteredValue': {'stringValue': 'Robinhood'}},
                                               {'effectiveFormat': {'backgroundColor': {'blue': 1,
                                                                                        'green': 1,
                                                                                        'red': 1},
                                                                    'horizontalAlignment': 'RIGHT',
                                                                    'hyperlinkDisplayType': 'PLAIN_TEXT',
                                                                    'padding': {'bottom': 2,
                                                                                'left': 3,
                                                                                'right': 3,
                                                                                'top': 2},
                                                                    'textFormat': {'bold': False,
                                                                                   'fontFamily': 'Arial',
                                                                                   'fontSize': 10,
                                                                                   'foregroundColor': {},
                                                                                   'italic': False,
                                                                                   'strikethrough': False,
                                                                                   'underline': False},
                                                                    'verticalAlignment': 'BOTTOM',
                                                                    'wrapStrategy': 'OVERFLOW_CELL'},
                                                'effectiveValue': {'numberValue': 20181017},
                                                'formattedValue': '20181017',
                                                'userEnteredValue': {'numberValue': 20181017}},
                                               {'effectiveFormat': {'backgroundColor': {'blue': 1,
                                                                                        'green': 1,
                                                                                        'red': 1},
                                                                    'padding': {'bottom': 2,
                                                                                'left': 3,
                                                                                'right': 3,
                                                                                'top': 2},
                                                                    'textFormat': {'bold': False,
                                                                                   'fontFamily': 'Arial',
                                                                                   'fontSize': 10,
                                                                                   'foregroundColor': {},
                                                                                   'italic': False,
                                                                                   'strikethrough': False,
                                                                                   'underline': False},
                                                                    'verticalAlignment': 'BOTTOM',
                                                                    'wrapStrategy': 'OVERFLOW_CELL'}}]},
                                   {'values': [{'effectiveFormat': {'backgroundColor': {'blue': 1,
                                                                                        'green': 1,
                                                                                        'red': 1},
                                                                    'horizontalAlignment': 'RIGHT',
                                                                    'hyperlinkDisplayType': 'PLAIN_TEXT',
                                                                    'padding': {'bottom': 2,
                                                                                'left': 3,
                                                                                'right': 3,
                                                                                'top': 2},
                                                                    'textFormat': {'bold': False,
                                                                                   'fontFamily': 'Arial',
                                                                                   'fontSize': 10,
                                                                                   'foregroundColor': {},
                                                                                   'italic': False,
                                                                                   'strikethrough': False,
                                                                                   'underline': False},
                                                                    'verticalAlignment': 'BOTTOM',
                                                                    'wrapStrategy': 'OVERFLOW_CELL'},
                                                'effectiveValue': {'numberValue': 43784},
                                                'formattedValue': '43784',
                                                'userEnteredValue': {'numberValue': 43784}},
                                               {'effectiveFormat': {'backgroundColor': {'blue': 1,
                                                                                        'green': 1,
                                                                                        'red': 1},
                                                                    'horizontalAlignment': 'LEFT',
                                                                    'hyperlinkDisplayType': 'PLAIN_TEXT',
                                                                    'padding': {'bottom': 2,
                                                                                'left': 3,
                                                                                'right': 3,
                                                                                'top': 2},
                                                                    'textFormat': {'bold': False,
                                                                                   'fontFamily': 'Arial',
                                                                                   'fontSize': 10,
                                                                                   'foregroundColor': {},
                                                                                   'italic': False,
                                                                                   'strikethrough': False,
                                                                                   'underline': False},
                                                                    'verticalAlignment': 'BOTTOM',
                                                                    'wrapStrategy': 'OVERFLOW_CELL'},
                                                'effectiveValue': {'stringValue': 'Investment '
                                                                                  'Asset'},
                                                'formattedValue': 'Investment '
                                                                  'Asset',
                                                'userEnteredValue': {'stringValue': 'Investment '
                                                                                    'Asset'}},
                                               {'effectiveFormat': {'backgroundColor': {'blue': 1,
                                                                                        'green': 1,
                                                                                        'red': 1},
                                                                    'horizontalAlignment': 'RIGHT',
                                                                    'hyperlinkDisplayType': 'PLAIN_TEXT',
                                                                    'padding': {'bottom': 2,
                                                                                'left': 3,
                                                                                'right': 3,
                                                                                'top': 2},
                                                                    'textFormat': {'bold': False,
                                                                                   'fontFamily': 'Arial',
                                                                                   'fontSize': 10,
                                                                                   'foregroundColor': {},
                                                                                   'italic': False,
                                                                                   'strikethrough': False,
                                                                                   'underline': False},
                                                                    'verticalAlignment': 'BOTTOM',
                                                                    'wrapStrategy': 'OVERFLOW_CELL'},
                                                'effectiveValue': {'numberValue': -4.67},
                                                'formattedValue': '-4.67',
                                                'userEnteredValue': {'numberValue': -4.67}},
                                               {'effectiveFormat': {'backgroundColor': {'blue': 1,
                                                                                        'green': 1,
                                                                                        'red': 1},
                                                                    'horizontalAlignment': 'LEFT',
                                                                    'hyperlinkDisplayType': 'PLAIN_TEXT',
                                                                    'padding': {'bottom': 2,
                                                                                'left': 3,
                                                                                'right': 3,
                                                                                'top': 2},
                                                                    'textFormat': {'bold': False,
                                                                                   'fontFamily': 'Arial',
                                                                                   'fontSize': 10,
                                                                                   'foregroundColor': {},
                                                                                   'italic': False,
                                                                                   'strikethrough': False,
                                                                                   'underline': False},
                                                                    'verticalAlignment': 'BOTTOM',
                                                                    'wrapStrategy': 'OVERFLOW_CELL'},
                                                'effectiveValue': {'stringValue': 'Hypothetical '
                                                                                  'Sale'},
                                                'formattedValue': 'Hypothetical '
                                                                  'Sale',
                                                'userEnteredValue': {'stringValue': 'Hypothetical '
                                                                                    'Sale'}},
                                               {'effectiveFormat': {'backgroundColor': {'blue': 1,
                                                                                        'green': 1,
                                                                                        'red': 1},
                                                                    'horizontalAlignment': 'LEFT',
                                                                    'hyperlinkDisplayType': 'PLAIN_TEXT',
                                                                    'padding': {'bottom': 2,
                                                                                'left': 3,
                                                                                'right': 3,
                                                                                'top': 2},
                                                                    'textFormat': {'bold': False,
                                                                                   'fontFamily': 'Arial',
                                                                                   'fontSize': 10,
                                                                                   'foregroundColor': {},
                                                                                   'italic': False,
                                                                                   'strikethrough': False,
                                                                                   'underline': False},
                                                                    'verticalAlignment': 'BOTTOM',
                                                                    'wrapStrategy': 'OVERFLOW_CELL'},
                                                'effectiveValue': {'stringValue': 'AKS'},
                                                'formattedValue': 'AKS',
                                                'userEnteredValue': {'stringValue': 'AKS'}},
                                               {'effectiveFormat': {'backgroundColor': {'blue': 1,
                                                                                        'green': 1,
                                                                                        'red': 1},
                                                                    'horizontalAlignment': 'LEFT',
                                                                    'hyperlinkDisplayType': 'PLAIN_TEXT',
                                                                    'padding': {'bottom': 2,
                                                                                'left': 3,
                                                                                'right': 3,
                                                                                'top': 2},
                                                                    'textFormat': {'bold': False,
                                                                                   'fontFamily': 'Arial',
                                                                                   'fontSize': 10,
                                                                                   'foregroundColor': {},
                                                                                   'italic': False,
                                                                                   'strikethrough': False,
                                                                                   'underline': False},
                                                                    'verticalAlignment': 'BOTTOM',
                                                                    'wrapStrategy': 'OVERFLOW_CELL'},
                                                'effectiveValue': {'stringValue': 'Robinhood'},
                                                'formattedValue': 'Robinhood',
                                                'userEnteredValue': {'stringValue': 'Robinhood'}},
                                               {'effectiveFormat': {'backgroundColor': {'blue': 1,
                                                                                        'green': 1,
                                                                                        'red': 1},
                                                                    'horizontalAlignment': 'RIGHT',
                                                                    'hyperlinkDisplayType': 'PLAIN_TEXT',
                                                                    'padding': {'bottom': 2,
                                                                                'left': 3,
                                                                                'right': 3,
                                                                                'top': 2},
                                                                    'textFormat': {'bold': False,
                                                                                   'fontFamily': 'Arial',
                                                                                   'fontSize': 10,
                                                                                   'foregroundColor': {},
                                                                                   'italic': False,
                                                                                   'strikethrough': False,
                                                                                   'underline': False},
                                                                    'verticalAlignment': 'BOTTOM',
                                                                    'wrapStrategy': 'OVERFLOW_CELL'},
                                                'effectiveValue': {'numberValue': 20181017},
                                                'formattedValue': '20181017',
                                                'userEnteredValue': {'numberValue': 20181017}},
                                               {'effectiveFormat': {'backgroundColor': {'blue': 1,
                                                                                        'green': 1,
                                                                                        'red': 1},
                                                                    'padding': {'bottom': 2,
                                                                                'left': 3,
                                                                                'right': 3,
                                                                                'top': 2},
                                                                    'textFormat': {'bold': False,
                                                                                   'fontFamily': 'Arial',
                                                                                   'fontSize': 10,
                                                                                   'foregroundColor': {},
                                                                                   'italic': False,
                                                                                   'strikethrough': False,
                                                                                   'underline': False},
                                                                    'verticalAlignment': 'BOTTOM',
                                                                    'wrapStrategy': 'OVERFLOW_CELL'}}]}],
                       'rowMetadata': [{'pixelSize': 21}, {'pixelSize': 21}]}],
             'properties': {'gridProperties': {'columnCount': 8, 'rowCount': 2},
                            'index': 8,
                            'sheetId': 909504350,
                            'sheetType': 'GRID',
                            'title': 'tempSheet'}}],
 'spreadsheetId': '1oisLtuJJOZnU-nMvILNWO43_8w2rCT3V6vq3vMnAnCI',
 'spreadsheetUrl': 'https://docs.google.com/spreadsheets/d/1oisLtuJJOZnU-nMvILNWO43_8w2rCT3V6vq3vMnAnCI/edit'}
{'properties': {'autoRecalc': 'ON_CHANGE',
                'defaultFormat': {'backgroundColor': {'blue': 1,
                                                      'green': 1,
                                                      'red': 1},
                                  'padding': {'bottom': 2,
                                              'left': 3,
                                              'right': 3,
                                              'top': 2},
                                  'textFormat': {'bold': False,
                                                 'fontFamily': 'arial,sans,sans-serif',
                                                 'fontSize': 10,
                                                 'foregroundColor': {},
                                                 'italic': False,
                                                 'strikethrough': False,
                                                 'underline': False},
                                  'verticalAlignment': 'BOTTOM',
                                  'wrapStrategy': 'OVERFLOW_CELL'},
                'locale': 'en_US',
                'timeZone': 'America/Denver',
                'title': 'Stock Results - Robinhood'},
 'sheets': [{'data': [{'columnMetadata': [{'pixelSize': 43},
                                          {'pixelSize': 107},
                                          {'pixelSize': 32},
                                          {'pixelSize': 108},
                                          {'pixelSize': 33},
                                          {'pixelSize': 70},
                                          {'pixelSize': 65},
                                          {'pixelSize': 14}],
                       'rowData': [{'values': [{'effectiveFormat': {'backgroundColor': {'blue': 1,
                                                                                        'green': 1,
                                                                                        'red': 1},
                                                                    'horizontalAlignment': 'RIGHT',
                                                                    'hyperlinkDisplayType': 'PLAIN_TEXT',
                                                                    'padding': {'bottom': 2,
                                                                                'left': 3,
                                                                                'right': 3,
                                                                                'top': 2},
                                                                    'textFormat': {'bold': False,
                                                                                   'fontFamily': 'Arial',
                                                                                   'fontSize': 10,
                                                                                   'foregroundColor': {},
                                                                                   'italic': False,
                                                                                   'strikethrough': False,
                                                                                   'underline': False},
                                                                    'verticalAlignment': 'BOTTOM',
                                                                    'wrapStrategy': 'OVERFLOW_CELL'},
                                                'effectiveValue': {'numberValue': 43784},
                                                'formattedValue': '43784',
                                                'userEnteredValue': {'numberValue': 43784}},
                                               {'effectiveFormat': {'backgroundColor': {'blue': 1,
                                                                                        'green': 1,
                                                                                        'red': 1},
                                                                    'horizontalAlignment': 'LEFT',
                                                                    'hyperlinkDisplayType': 'PLAIN_TEXT',
                                                                    'padding': {'bottom': 2,
                                                                                'left': 3,
                                                                                'right': 3,
                                                                                'top': 2},
                                                                    'textFormat': {'bold': False,
                                                                                   'fontFamily': 'Arial',
                                                                                   'fontSize': 10,
                                                                                   'foregroundColor': {},
                                                                                   'italic': False,
                                                                                   'strikethrough': False,
                                                                                   'underline': False},
                                                                    'verticalAlignment': 'BOTTOM',
                                                                    'wrapStrategy': 'OVERFLOW_CELL'},
                                                'effectiveValue': {'stringValue': 'Cash'},
                                                'formattedValue': 'Cash',
                                                'userEnteredValue': {'stringValue': 'Cash'}},
                                               {'effectiveFormat': {'backgroundColor': {'blue': 1,
                                                                                        'green': 1,
                                                                                        'red': 1},
                                                                    'horizontalAlignment': 'RIGHT',
                                                                    'hyperlinkDisplayType': 'PLAIN_TEXT',
                                                                    'padding': {'bottom': 2,
                                                                                'left': 3,
                                                                                'right': 3,
                                                                                'top': 2},
                                                                    'textFormat': {'bold': False,
                                                                                   'fontFamily': 'Arial',
                                                                                   'fontSize': 10,
                                                                                   'foregroundColor': {},
                                                                                   'italic': False,
                                                                                   'strikethrough': False,
                                                                                   'underline': False},
                                                                    'verticalAlignment': 'BOTTOM',
                                                                    'wrapStrategy': 'OVERFLOW_CELL'},
                                                'effectiveValue': {'numberValue': 2.55},
                                                'formattedValue': '2.55',
                                                'userEnteredValue': {'formulaValue': '=GOOGLEFINANCE("AKS")*INDIRECT("H"&ROW())'}},
                                               {'effectiveFormat': {'backgroundColor': {'blue': 1,
                                                                                        'green': 1,
                                                                                        'red': 1},
                                                                    'horizontalAlignment': 'LEFT',
                                                                    'hyperlinkDisplayType': 'PLAIN_TEXT',
                                                                    'padding': {'bottom': 2,
                                                                                'left': 3,
                                                                                'right': 3,
                                                                                'top': 2},
                                                                    'textFormat': {'bold': False,
                                                                                   'fontFamily': 'Arial',
                                                                                   'fontSize': 10,
                                                                                   'foregroundColor': {},
                                                                                   'italic': False,
                                                                                   'strikethrough': False,
                                                                                   'underline': False},
                                                                    'verticalAlignment': 'BOTTOM',
                                                                    'wrapStrategy': 'OVERFLOW_CELL'},
                                                'effectiveValue': {'stringValue': 'Hypothetical '
                                                                                  'Sale'},
                                                'formattedValue': 'Hypothetical '
                                                                  'Sale',
                                                'userEnteredValue': {'stringValue': 'Hypothetical '
                                                                                    'Sale'}},
                                               {'effectiveFormat': {'backgroundColor': {'blue': 1,
                                                                                        'green': 1,
                                                                                        'red': 1},
                                                                    'horizontalAlignment': 'LEFT',
                                                                    'hyperlinkDisplayType': 'PLAIN_TEXT',
                                                                    'padding': {'bottom': 2,
                                                                                'left': 3,
                                                                                'right': 3,
                                                                                'top': 2},
                                                                    'textFormat': {'bold': False,
                                                                                   'fontFamily': 'Arial',
                                                                                   'fontSize': 10,
                                                                                   'foregroundColor': {},
                                                                                   'italic': False,
                                                                                   'strikethrough': False,
                                                                                   'underline': False},
                                                                    'verticalAlignment': 'BOTTOM',
                                                                    'wrapStrategy': 'OVERFLOW_CELL'},
                                                'effectiveValue': {'stringValue': 'AKS'},
                                                'formattedValue': 'AKS',
                                                'userEnteredValue': {'stringValue': 'AKS'}},
                                               {'effectiveFormat': {'backgroundColor': {'blue': 1,
                                                                                        'green': 1,
                                                                                        'red': 1},
                                                                    'horizontalAlignment': 'LEFT',
                                                                    'hyperlinkDisplayType': 'PLAIN_TEXT',
                                                                    'padding': {'bottom': 2,
                                                                                'left': 3,
                                                                                'right': 3,
                                                                                'top': 2},
                                                                    'textFormat': {'bold': False,
                                                                                   'fontFamily': 'Arial',
                                                                                   'fontSize': 10,
                                                                                   'foregroundColor': {},
                                                                                   'italic': False,
                                                                                   'strikethrough': False,
                                                                                   'underline': False},
                                                                    'verticalAlignment': 'BOTTOM',
                                                                    'wrapStrategy': 'OVERFLOW_CELL'},
                                                'effectiveValue': {'stringValue': 'Robinhood'},
                                                'formattedValue': 'Robinhood',
                                                'userEnteredValue': {'stringValue': 'Robinhood'}},
                                               {'effectiveFormat': {'backgroundColor': {'blue': 1,
                                                                                        'green': 1,
                                                                                        'red': 1},
                                                                    'horizontalAlignment': 'RIGHT',
                                                                    'hyperlinkDisplayType': 'PLAIN_TEXT',
                                                                    'padding': {'bottom': 2,
                                                                                'left': 3,
                                                                                'right': 3,
                                                                                'top': 2},
                                                                    'textFormat': {'bold': False,
                                                                                   'fontFamily': 'Arial',
                                                                                   'fontSize': 10,
                                                                                   'foregroundColor': {},
                                                                                   'italic': False,
                                                                                   'strikethrough': False,
                                                                                   'underline': False},
                                                                    'verticalAlignment': 'BOTTOM',
                                                                    'wrapStrategy': 'OVERFLOW_CELL'},
                                                'effectiveValue': {'numberValue': 20181017},
                                                'formattedValue': '20181017',
                                                'userEnteredValue': {'numberValue': 20181017}},
                                               {'effectiveFormat': {'backgroundColor': {'blue': 1,
                                                                                        'green': 1,
                                                                                        'red': 1},
                                                                    'horizontalAlignment': 'RIGHT',
                                                                    'hyperlinkDisplayType': 'PLAIN_TEXT',
                                                                    'padding': {'bottom': 2,
                                                                                'left': 3,
                                                                                'right': 3,
                                                                                'top': 2},
                                                                    'textFormat': {'bold': False,
                                                                                   'fontFamily': 'Arial',
                                                                                   'fontSize': 10,
                                                                                   'foregroundColor': {},
                                                                                   'italic': False,
                                                                                   'strikethrough': False,
                                                                                   'underline': False},
                                                                    'verticalAlignment': 'BOTTOM',
                                                                    'wrapStrategy': 'OVERFLOW_CELL'},
                                                'effectiveValue': {'numberValue': 1},
                                                'formattedValue': '1',
                                                'userEnteredValue': {'numberValue': 1}}]},
                                   {'values': [{'effectiveFormat': {'backgroundColor': {'blue': 1,
                                                                                        'green': 1,
                                                                                        'red': 1},
                                                                    'horizontalAlignment': 'RIGHT',
                                                                    'hyperlinkDisplayType': 'PLAIN_TEXT',
                                                                    'padding': {'bottom': 2,
                                                                                'left': 3,
                                                                                'right': 3,
                                                                                'top': 2},
                                                                    'textFormat': {'bold': False,
                                                                                   'fontFamily': 'Arial',
                                                                                   'fontSize': 10,
                                                                                   'foregroundColor': {},
                                                                                   'italic': False,
                                                                                   'strikethrough': False,
                                                                                   'underline': False},
                                                                    'verticalAlignment': 'BOTTOM',
                                                                    'wrapStrategy': 'OVERFLOW_CELL'},
                                                'effectiveValue': {'numberValue': 43784},
                                                'formattedValue': '43784',
                                                'userEnteredValue': {'numberValue': 43784}},
                                               {'effectiveFormat': {'backgroundColor': {'blue': 1,
                                                                                        'green': 1,
                                                                                        'red': 1},
                                                                    'horizontalAlignment': 'LEFT',
                                                                    'hyperlinkDisplayType': 'PLAIN_TEXT',
                                                                    'padding': {'bottom': 2,
                                                                                'left': 3,
                                                                                'right': 3,
                                                                                'top': 2},
                                                                    'textFormat': {'bold': False,
                                                                                   'fontFamily': 'Arial',
                                                                                   'fontSize': 10,
                                                                                   'foregroundColor': {},
                                                                                   'italic': False,
                                                                                   'strikethrough': False,
                                                                                   'underline': False},
                                                                    'verticalAlignment': 'BOTTOM',
                                                                    'wrapStrategy': 'OVERFLOW_CELL'},
                                                'effectiveValue': {'stringValue': 'Investment '
                                                                                  'Asset'},
                                                'formattedValue': 'Investment '
                                                                  'Asset',
                                                'userEnteredValue': {'stringValue': 'Investment '
                                                                                    'Asset'}},
                                               {'effectiveFormat': {'backgroundColor': {'blue': 1,
                                                                                        'green': 1,
                                                                                        'red': 1},
                                                                    'horizontalAlignment': 'RIGHT',
                                                                    'hyperlinkDisplayType': 'PLAIN_TEXT',
                                                                    'padding': {'bottom': 2,
                                                                                'left': 3,
                                                                                'right': 3,
                                                                                'top': 2},
                                                                    'textFormat': {'bold': False,
                                                                                   'fontFamily': 'Arial',
                                                                                   'fontSize': 10,
                                                                                   'foregroundColor': {},
                                                                                   'italic': False,
                                                                                   'strikethrough': False,
                                                                                   'underline': False},
                                                                    'verticalAlignment': 'BOTTOM',
                                                                    'wrapStrategy': 'OVERFLOW_CELL'},
                                                'effectiveValue': {'numberValue': 0},
                                                'formattedValue': '0',
                                                'userEnteredValue': {'numberValue': 0}},
                                               {'effectiveFormat': {'backgroundColor': {'blue': 1,
                                                                                        'green': 1,
                                                                                        'red': 1},
                                                                    'horizontalAlignment': 'LEFT',
                                                                    'hyperlinkDisplayType': 'PLAIN_TEXT',
                                                                    'padding': {'bottom': 2,
                                                                                'left': 3,
                                                                                'right': 3,
                                                                                'top': 2},
                                                                    'textFormat': {'bold': False,
                                                                                   'fontFamily': 'Arial',
                                                                                   'fontSize': 10,
                                                                                   'foregroundColor': {},
                                                                                   'italic': False,
                                                                                   'strikethrough': False,
                                                                                   'underline': False},
                                                                    'verticalAlignment': 'BOTTOM',
                                                                    'wrapStrategy': 'OVERFLOW_CELL'},
                                                'effectiveValue': {'stringValue': 'Hypothetical '
                                                                                  'Sale'},
                                                'formattedValue': 'Hypothetical '
                                                                  'Sale',
                                                'userEnteredValue': {'stringValue': 'Hypothetical '
                                                                                    'Sale'}},
                                               {'effectiveFormat': {'backgroundColor': {'blue': 1,
                                                                                        'green': 1,
                                                                                        'red': 1},
                                                                    'horizontalAlignment': 'LEFT',
                                                                    'hyperlinkDisplayType': 'PLAIN_TEXT',
                                                                    'padding': {'bottom': 2,
                                                                                'left': 3,
                                                                                'right': 3,
                                                                                'top': 2},
                                                                    'textFormat': {'bold': False,
                                                                                   'fontFamily': 'Arial',
                                                                                   'fontSize': 10,
                                                                                   'foregroundColor': {},
                                                                                   'italic': False,
                                                                                   'strikethrough': False,
                                                                                   'underline': False},
                                                                    'verticalAlignment': 'BOTTOM',
                                                                    'wrapStrategy': 'OVERFLOW_CELL'},
                                                'effectiveValue': {'stringValue': 'AKS'},
                                                'formattedValue': 'AKS',
                                                'userEnteredValue': {'stringValue': 'AKS'}},
                                               {'effectiveFormat': {'backgroundColor': {'blue': 1,
                                                                                        'green': 1,
                                                                                        'red': 1},
                                                                    'horizontalAlignment': 'LEFT',
                                                                    'hyperlinkDisplayType': 'PLAIN_TEXT',
                                                                    'padding': {'bottom': 2,
                                                                                'left': 3,
                                                                                'right': 3,
                                                                                'top': 2},
                                                                    'textFormat': {'bold': False,
                                                                                   'fontFamily': 'Arial',
                                                                                   'fontSize': 10,
                                                                                   'foregroundColor': {},
                                                                                   'italic': False,
                                                                                   'strikethrough': False,
                                                                                   'underline': False},
                                                                    'verticalAlignment': 'BOTTOM',
                                                                    'wrapStrategy': 'OVERFLOW_CELL'},
                                                'effectiveValue': {'stringValue': 'Robinhood'},
                                                'formattedValue': 'Robinhood',
                                                'userEnteredValue': {'stringValue': 'Robinhood'}},
                                               {'effectiveFormat': {'backgroundColor': {'blue': 1,
                                                                                        'green': 1,
                                                                                        'red': 1},
                                                                    'horizontalAlignment': 'RIGHT',
                                                                    'hyperlinkDisplayType': 'PLAIN_TEXT',
                                                                    'padding': {'bottom': 2,
                                                                                'left': 3,
                                                                                'right': 3,
                                                                                'top': 2},
                                                                    'textFormat': {'bold': False,
                                                                                   'fontFamily': 'Arial',
                                                                                   'fontSize': 10,
                                                                                   'foregroundColor': {},
                                                                                   'italic': False,
                                                                                   'strikethrough': False,
                                                                                   'underline': False},
                                                                    'verticalAlignment': 'BOTTOM',
                                                                    'wrapStrategy': 'OVERFLOW_CELL'},
                                                'effectiveValue': {'numberValue': 20181017},
                                                'formattedValue': '20181017',
                                                'userEnteredValue': {'numberValue': 20181017}},
                                               {'effectiveFormat': {'backgroundColor': {'blue': 1,
                                                                                        'green': 1,
                                                                                        'red': 1},
                                                                    'horizontalAlignment': 'RIGHT',
                                                                    'hyperlinkDisplayType': 'PLAIN_TEXT',
                                                                    'padding': {'bottom': 2,
                                                                                'left': 3,
                                                                                'right': 3,
                                                                                'top': 2},
                                                                    'textFormat': {'bold': False,
                                                                                   'fontFamily': 'Arial',
                                                                                   'fontSize': 10,
                                                                                   'foregroundColor': {},
                                                                                   'italic': False,
                                                                                   'strikethrough': False,
                                                                                   'underline': False},
                                                                    'verticalAlignment': 'BOTTOM',
                                                                    'wrapStrategy': 'OVERFLOW_CELL'},
                                                'effectiveValue': {'numberValue': 1},
                                                'formattedValue': '1',
                                                'userEnteredValue': {'numberValue': 1}}]}],
                       'rowMetadata': [{'pixelSize': 21}, {'pixelSize': 21}]}],
             'properties': {'gridProperties': {'columnCount': 8, 'rowCount': 2},
                            'index': 8,
                            'sheetId': 909504350,
                            'sheetType': 'GRID',
                            'title': 'tempSheet'}}],
 'spreadsheetId': '1oisLtuJJOZnU-nMvILNWO43_8w2rCT3V6vq3vMnAnCI',
 'spreadsheetUrl': 'https://docs.google.com/spreadsheets/d/1oisLtuJJOZnU-nMvILNWO43_8w2rCT3V6vq3vMnAnCI/edit'}
