#!/bin/zsh

red='\033[0;31m'
green='\033[0;32m'
blue='\033[0;34m'
purple='\033[0;35m'
cyan='\033[0;36m'
yellow='\033[1;33m'
lightCyan='\033[1;36m'
noColor='\033[0m'

echo ''
echo -e "${lightCyan}command: pyenv versions${noColor}"
pyenv versions

echo ''
echo -e "${red}command: pyenv which python${noColor}"
pyenv which python

echo ''
echo -e "${red}command: pyenv which pip${noColor}"
pyenv which pip

echo ''
echo -e "${green}command: pyenv which python3.9${noColor}"
pyenv which python3

echo ''
echo -e "${green}command: pyenv which pip${noColor}"
pyenv which pip3

echo ''
echo -e "${blue}command: which python${noColor}"
which python

echo ''
echo -e "${blue}command: python --version${noColor}"
python --version

echo ''
echo -e "${purple}command: which pip${noColor}"
which pip

echo ''
echo -e "${purple}command: pip --version${noColor}"
pip --version

echo ''
echo -e "${cyan}command: which python3${noColor}"
which python3

echo ''
echo -e "${cyan}command: python3 --version${noColor}"
python3 --version

echo ''
echo -e "${yellow}command: which pip3${noColor}"
which pip3

echo ''
echo -e "${yellow}command: pip3 --version${noColor}"
pip3 --version
