#!/bin/bash

# echo $@
pathToThisFileDirectory="$(dirname $(greadlink -f $0))"
# echo $pathToThisFileDirectory

pythonExeToUse=$pathToThisFileDirectory/../../../pythonVirtualEnvs/env/bin/python3
$pythonExeToUse $pathToThisFileDirectory/moduleImporters/pythonModuleImporter.py $@