#!/bin/bash

pathToThisFileDirectoryLinuxFormat="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
# echo $pathToThisFileDirectoryLinuxFormat
pathToFileWithVariable="$pathToThisFileDirectoryLinuxFormat/../../privateData/commandLineLetterSpace/fileWithVariable.sh"

source $pathToFileWithVariable
# echo $variableFromFile

modifiedDirectory="c:${pathToThisFileDirectoryLinuxFormat:6}/pythonModuleImporter.py"
# echo $modifiedDirectory
pathToThisFileDirectoryWindowsFormat=${modifiedDirectory//\//\\}
commandToExecute="$variableFromFile $pathToThisFileDirectoryWindowsFormat $@"
# echo $commandToExecute
$commandToExecute
